### ISSUE TITLE
Error while running mystique.py

### ISSUE THREAD

**Issue by DefenderLab** [MinervaLabsResearch/Mystique#2]
Hi,

I have installed cuckoo 2.0.6.2
I'm facing issue while running mystique.py

$ python mystique.py {path} 
http://localhost:8000/tasks/create/file  <--- I have print this
{'file': ('/home/admin1/Downloads/tmp/asd.exe', <open file '/home/admin1/Downloads/tmp/asd.exe', mode 'rb' at 0x7f86c8995420>)}   <--- I have print this
{'machine': u'cuckoo2'}       <--- I have print this
<Response [404]>             <--- I have print this

oh : [
Traceback (most recent call last):
  File "mystique.py", line 426, in main
    first_id = submit_sample(sample_file, guest_machine_name)
  File "mystique.py", line 163, in submit_sample
    print r.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
None
----------------------------------------------------------------
http://{cuckoo url}/tasks/create/file  
this link isn't available.

**Comment by GelosSnake** [comment]
Thanks @DefenderLab , is the cuckoo API currently running on your cuckoo installation?
